import Foundation
import XCTest

final class AddClusterProcessE2EContractTests: XCTestCase {
    func testProcessE2EStartsEmptyImportsOnlyLocalComposeContextsAndChecksActivation() throws {
        let script = try source("scripts/run-add-cluster-import-e2e.sh")

        XCTAssertFalse(script.contains("RUNE_ISOLATED_KUBECONFIG"))
        XCTAssertFalse(script.contains("defaults write"))
        XCTAssertFalse(script.contains("defaults read"))
        let compileLauncher = try XCTUnwrap(script.range(of: "scripts/rune-app-launch.swift"))
        let launch = try XCTUnwrap(script.range(of: "\"$LAUNCH_HELPER\" \"$TEST_APP_BUNDLE\" \"$TEST_STATE_DIR\""))
        XCTAssertLessThan(compileLauncher.lowerBound, launch.lowerBound)
        XCTAssertTrue(script.contains("name: fake-orbit-mesh"))
        XCTAssertTrue(script.contains("name: fake-lattice-spark"))
        XCTAssertTrue(script.contains("server: https://127.0.0.1:16443"))
        XCTAssertTrue(script.contains("server: https://127.0.0.1:17443"))
        XCTAssertTrue(script.contains("\"$AX_HELPER\" \"$APP_PID\" import-kubeconfig"))
        XCTAssertTrue(script.contains("expected_import_result=\"import-kubeconfig-e2e passed route=add-cluster-popover contexts=2 source=app-owned\""))
        XCTAssertTrue(script.contains("if [[ \"$import_result\" != \"$expected_import_result\" ]]"))
        XCTAssertTrue(script.contains("RUNE_APP_LAUNCH_ENABLE_DEMO_CLUSTER=1"))
        XCTAssertTrue(script.contains("TEST_APP_BUNDLE=\"$TEST_STATE_DIR/RuneAddClusterE2E.app\""))
        XCTAssertTrue(script.contains("TEST_BUNDLE_IDENTIFIER=\"app.rune.local.e2e.add-cluster.$$\""))
        XCTAssertTrue(script.contains("plutil -replace CFBundleIdentifier"))
        XCTAssertTrue(script.contains("codesign --verify --deep --strict \"$TEST_APP_BUNDLE\""))
        XCTAssertTrue(script.contains("scripts/rune-app-launch.swift"))
        XCTAssertTrue(script.contains("IMPORT_ROOT=\"$TEST_STATE_DIR/Library/Application Support/Rune/kubeconfigs/imports\""))
        XCTAssertTrue(script.contains("if [[ \"$imported_count\" != \"1\" ]]"))
        XCTAssertTrue(script.contains("IMPORTED_KUBECONFIG="))
        XCTAssertTrue(script.contains("RUNE_UI_SMOKE_IMPORT_ROOT=\"$IMPORT_ROOT\""))
        XCTAssertTrue(script.contains("namespace-lists/fake-orbit-mesh.json"))
        XCTAssertTrue(script.contains("rm -f \"$ACTIVATION_PROOF\""))
        XCTAssertTrue(script.contains("RUNE_UI_SMOKE_ACTIVATION_PROOF=\"$ACTIVATION_PROOF\""))
        XCTAssertTrue(script.contains("kubectl --kubeconfig \"$IMPORTED_KUBECONFIG\" config get-contexts -o name"))
        XCTAssertTrue(script.contains("if [[ \"$imported_contexts\" != \"fake-lattice-spark fake-orbit-mesh \" ]]"))
        XCTAssertTrue(script.contains("expected_contexts=(\"fake-orbit-mesh\" \"fake-lattice-spark\")"))
        XCTAssertTrue(script.contains("expected_namespaces=(\"alpha-zone\" \"delta-zone\")"))
        XCTAssertTrue(script.contains("--context \"$expected_context\""))
        XCTAssertTrue(script.contains("get --raw=/readyz"))
        XCTAssertTrue(script.contains("get namespace \"$expected_namespace\" -o name"))
        XCTAssertTrue(script.contains("grep -Fq '\"alpha-zone\"' \"$ACTIVATION_PROOF\""))
        XCTAssertTrue(script.contains("grep -Fq '\"bravo-zone\"' \"$ACTIVATION_PROOF\""))
        XCTAssertTrue(script.contains("Rune never completed a live namespace read for the activated context"))
        XCTAssertTrue(script.contains("app-context-loaded=1"))
        XCTAssertTrue(script.contains("readyz=2 resource-reads=2"))
        XCTAssertTrue(script.contains("\"$LAUNCH_HELPER\" --terminate \"$TEST_APP_BUNDLE\" \"$APP_PID\""))
        XCTAssertTrue(script.contains("Refusing to signal Rune PID $APP_PID without the ownership-checking launch helper."))
        XCTAssertFalse(script.contains("pkill"))
        XCTAssertFalse(script.contains("kill \"$APP_PID\""))
        let importedPathResolution = try XCTUnwrap(script.range(of: "IMPORTED_KUBECONFIG="))
        let importRouteInvocation = try XCTUnwrap(script.range(of: "\"$AX_HELPER\" \"$APP_PID\" import-kubeconfig"))
        let importRouteValidation = try XCTUnwrap(
            script.range(of: "if [[ \"$import_result\" != \"$expected_import_result\" ]]")
        )
        let importedCountValidation = try XCTUnwrap(
            script.range(of: "if [[ \"$imported_count\" != \"1\" ]]")
        )
        let importedContextValidation = try XCTUnwrap(
            script.range(of: "kubectl --kubeconfig \"$IMPORTED_KUBECONFIG\" config get-contexts -o name")
        )
        let importedReadinessProbe = try XCTUnwrap(
            script.range(of: "kubectl --kubeconfig \"$IMPORTED_KUBECONFIG\" \\\n      --context \"$expected_context\"")
        )
        XCTAssertLessThan(importRouteInvocation.lowerBound, importRouteValidation.lowerBound)
        XCTAssertLessThan(importRouteValidation.lowerBound, importedCountValidation.lowerBound)
        XCTAssertLessThan(importedPathResolution.lowerBound, importedContextValidation.lowerBound)
        XCTAssertLessThan(importedContextValidation.lowerBound, importedReadinessProbe.lowerBound)
        XCTAssertTrue(
            FileManager.default.isExecutableFile(
                atPath: repoRoot.appendingPathComponent("scripts/run-add-cluster-import-e2e.sh").path
            )
        )
    }

    func testLaunchHelperUsesAppKitWithAnIsolatedHomeAndNoRecentItemSideEffect() throws {
        let launcher = try source("scripts/rune-app-launch.swift")

        XCTAssertTrue(launcher.contains("NSWorkspace.OpenConfiguration()"))
        XCTAssertTrue(launcher.contains("configuration.activates = true"))
        XCTAssertTrue(launcher.contains("configuration.addsToRecentItems = false"))
        XCTAssertTrue(launcher.contains("configuration.createsNewApplicationInstance = true"))
        XCTAssertTrue(launcher.contains("RUNE_APP_LAUNCH_ENABLE_DEMO_CLUSTER"))
        XCTAssertTrue(launcher.contains("enableDemoCluster ? \"true\" : \"false\""))
        XCTAssertTrue(launcher.contains("\"HOME\": isolatedHome.path"))
        XCTAssertTrue(launcher.contains("\"CFFIXED_USER_HOME\": isolatedHome.path"))
        XCTAssertTrue(launcher.contains("RUNE_DISABLE_DEFAULT_KUBECONFIG_DISCOVERY"))
        XCTAssertTrue(launcher.contains("RUNE_DISABLE_BOOKMARKED_KUBECONFIGS"))
        XCTAssertTrue(launcher.contains("if invokingEnvironment[\"RUNE_APP_LAUNCH_FORWARD_UI_SMOKE_ENV\"] == \"1\""))
        XCTAssertTrue(launcher.contains("print(application.processIdentifier)"))

        let ownershipCheck = try XCTUnwrap(launcher.range(of: "guard let application = try testOwnedApplication("))
        let gracefulTermination = try XCTUnwrap(launcher.range(of: "application.terminate()"))
        let gracefulWait = try XCTUnwrap(launcher.range(of: "if await waitForTermination(of: application)"))
        let forceOwnershipCheck = try XCTUnwrap(launcher.range(of: "guard let forceTarget = try testOwnedApplication("))
        let forcedTermination = try XCTUnwrap(launcher.range(of: "forceTarget.forceTerminate()"))
        XCTAssertLessThan(ownershipCheck.lowerBound, gracefulTermination.lowerBound)
        XCTAssertLessThan(gracefulTermination.lowerBound, gracefulWait.lowerBound)
        XCTAssertLessThan(gracefulWait.lowerBound, forceOwnershipCheck.lowerBound)
        XCTAssertLessThan(forceOwnershipCheck.lowerBound, forcedTermination.lowerBound)
        XCTAssertTrue(launcher.contains("actualBundleURL == expectedBundleURL"))
        XCTAssertTrue(launcher.contains("application.bundleIdentifier == expectedBundleIdentifier"))
        XCTAssertTrue(launcher.contains("NSRunningApplication(processIdentifier: processIdentifier)"))
        XCTAssertTrue(launcher.contains("Darwin.kill(processIdentifier, 0)"))
        XCTAssertEqual(launcher.components(separatedBy: "try testOwnedApplication(").count - 1, 2)
        XCTAssertTrue(launcher.contains("for _ in 0..<40"))
    }

    func testAccessibilityDriverUsesStableImportIdentifiersAndRequiresExplicitLocalFixture() throws {
        let driver = try source("scripts/rune-ui-smoke-ax.swift")
        let onboarding = try source("Sources/RuneUI/Views/KubernetesConnectionOnboardingView.swift")
        let review = try source("Sources/RuneUI/Views/KubeConfigImportReviewPanel.swift")
        let contextRow = try source("Sources/RuneUI/Views/ContextSidebarRow.swift")
        let app = try source("Sources/RuneApp/RuneApp.swift")

        XCTAssertTrue(driver.contains("case \"import-kubeconfig\""))
        XCTAssertTrue(driver.contains("RUNE_UI_SMOKE_IMPORT_KUBECONFIG"))
        XCTAssertTrue(driver.contains("rune.onboarding.connection-methods"))
        XCTAssertTrue(driver.contains("rune.onboarding.paste-kubeconfig"))
        XCTAssertTrue(driver.contains("rune.add-cluster.button"))
        XCTAssertTrue(driver.contains("importRoute = \"add-cluster-popover\""))
        XCTAssertTrue(driver.contains("paste local fake kubeconfig through Add Cluster"))
        XCTAssertTrue(driver.contains("rune.kubeconfig-import.review"))
        XCTAssertTrue(driver.contains("rune.kubeconfig-import.confirm"))
        XCTAssertTrue(driver.contains("rune.kubeconfig-import.context.fake-orbit-mesh"))
        XCTAssertTrue(driver.contains("rune.kubeconfig-import.context.fake-lattice-spark"))
        XCTAssertTrue(driver.contains("rune.kubeconfig-import.status"))
        XCTAssertTrue(driver.contains("rune.context.fake-orbit-mesh"))
        XCTAssertTrue(driver.contains("rune.context.fake-lattice-spark"))
        XCTAssertTrue(driver.contains("isSelected(orbitContext)"))
        XCTAssertTrue(driver.contains("private func applicationWindows(_ root: AXUIElement)"))
        XCTAssertTrue(driver.contains("stack.append(contentsOf: children(of: root))"))
        XCTAssertTrue(driver.contains("kAXFocusedWindowAttribute"))
        XCTAssertTrue(driver.contains("kAXMainWindowAttribute"))
        XCTAssertTrue(driver.contains("kAXFrontmostAttribute"))
        XCTAssertTrue(driver.contains(".activateAllWindows"))
        XCTAssertTrue(driver.contains("clickTitlebarOfOnScreenLayerZeroWindow(processID: processID)"))
        XCTAssertTrue(driver.contains("kCGWindowOwnerPID as String"))
        XCTAssertTrue(driver.contains("kCGWindowLayer as String"))
        XCTAssertTrue(driver.contains("but no AXWindow materialized"))
        XCTAssertTrue(driver.contains("!CFEqual(candidate, root)"))
        XCTAssertTrue(driver.contains("kAXWindowRole as String"))
        XCTAssertTrue(driver.contains("if !applicationWindows(root).isEmpty"))
        XCTAssertFalse(driver.contains("postKey(45, flags: .maskCommand"))
        XCTAssertTrue(driver.contains("private struct AXElementIdentitySet"))
        XCTAssertTrue(driver.contains("let hash = CFHash(element)"))
        XCTAssertTrue(driver.contains("CFEqual($0, element)"))
        XCTAssertTrue(driver.contains("guard visited.insert(element) else { continue }"))
        XCTAssertTrue(driver.contains("RUNE_UI_SMOKE_IMPORT_ROOT"))
        XCTAssertTrue(driver.contains("RUNE_UI_SMOKE_ACTIVATION_PROOF"))
        XCTAssertTrue(driver.contains("containsActivatedContextProof(at: activationProof)"))
        XCTAssertTrue(driver.contains("app-context-loaded=1"))
        XCTAssertTrue(driver.contains("role: kAXMenuItemRole as String"))
        XCTAssertTrue(driver.contains("invoke native Paste Kubeconfig command"))
        XCTAssertTrue(driver.contains("postKey(36, to: processID)"))
        XCTAssertTrue(app.contains("Button(\"Paste Kubeconfig\")"))
        XCTAssertFalse(app.contains(".keyboardShortcut(\"v\", modifiers: [.command, .shift])"))
        XCTAssertTrue(onboarding.contains(".accessibilityIdentifier(\"rune.onboarding.connection-methods\")"))
        XCTAssertTrue(onboarding.contains(".accessibilityIdentifier(\"rune.onboarding.paste-kubeconfig\")"))
        XCTAssertTrue(review.contains(".accessibilityIdentifier(\"rune.kubeconfig-import.review\")"))
        XCTAssertTrue(review.contains(".accessibilityIdentifier(\"rune.kubeconfig-import.confirm\")"))
        XCTAssertTrue(review.contains(".accessibilityIdentifier(\"rune.kubeconfig-import.status\")"))
        XCTAssertTrue(review.contains(".accessibilityIdentifier(\"rune.kubeconfig-import.context.\\(context.name)\")"))
        XCTAssertTrue(contextRow.contains(".accessibilityIdentifier(\"rune.context.\\(rawName)\")"))
        XCTAssertTrue(contextRow.contains(".accessibilityValue(isSelected ? \"Selected\" : \"Not selected\")"))
    }

    private func source(_ relativePath: String) throws -> String {
        try String(contentsOf: repoRoot.appendingPathComponent(relativePath), encoding: .utf8)
    }

    private var repoRoot: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
    }
}
